name = "ArtifactUtils"
uuid = "8b73e784-e7d8-4ea5-973d-377fed4e3bce"
authors = ["Simeon Schaub <simeondavidschaub99@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"

[compat]
julia = "1.3"

[extras]
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "TOML"]
